"""add player_odds table

Revision ID: 17c46971f820
Revises: dffd9fce6014
Create Date: 2026-09-17 19:14:58.249057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17c46971f820'
down_revision: Union[str, Sequence[str], None] = 'dffd9fce6014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_odds',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('player_id', sa.String(length=36), nullable=False),
    sa.Column('gameweek_id', sa.String(length=36), nullable=False),
    sa.Column('prop_market_id', sa.String(length=36), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('odds_decimal', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['gameweek_id'], ['gameweek.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['prop_market_id'], ['prop_market.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_odds')
    # ### end Alembic commands ###
