"""add fixture table

Revision ID: dffd9fce6014
Revises: 253ad1386eb8
Create Date: 2026-09-15 15:17:33.860300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dffd9fce6014'
down_revision: Union[str, Sequence[str], None] = '253ad1386eb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fixture',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('gameweek_id', sa.String(length=36), nullable=False),
    sa.Column('fpl_fixture_id', sa.Integer(), nullable=False),
    sa.Column('home_team', sa.String(length=32), nullable=False),
    sa.Column('away_team', sa.String(length=32), nullable=False),
    sa.Column('kickoff_time', sa.DateTime(), nullable=False),
    sa.Column('finished', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['gameweek_id'], ['gameweek.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fpl_fixture_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fixture')
    # ### end Alembic commands ###
